# Generated by Django 5.1.6 on 2025-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='description',
            new_name='full_description',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='short_description',
            field=models.CharField(default='No description', max_length=255),
            preserve_default=False,
        ),
    ]
