# Generated by Django 5.1.6 on 2025-02-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0003_proyecto_destacado'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('image', models.ImageField(upload_to='hobby_images/', verbose_name='Imagen')),
            ],
        ),
    ]
