# Generated by Django 5.1.6 on 2025-02-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0004_hobbyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='technical_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción Técnica'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video Extra'),
        ),
    ]
