# Generated by Django 5.1.6 on 2025-02-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0005_proyecto_technical_description_proyecto_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/', verbose_name='Video Extra'),
        ),
    ]
