# Generated by Django 5.1.6 on 2025-02-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0008_alter_proyecto_tecnologias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('Web', 'Web'), ('Escritorio', 'Escritorio'), ('Móvil', 'Móvil')], default='Web', max_length=10, verbose_name='Tipo de Proyecto'),
        ),
    ]
